### PR TITLE
Add support for tmux (#3)

### LINKED ISSUE #3: tmux support
Some articles to get started:
https://sunaku.github.io/tmux-yank-osc52.html
https://medium.com/free-code-camp/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b

### PR DESCRIPTION
**Pull request by Javex**
This should fix https://github.com/theimpostor/osc/issues/3

### CODE REVIEW

**Comment by theimpostor** [comment]
Thanks! Does this require the tmux `allow-passthrough` option to be enabled, and if so is there any way to check programmatically if it is enabled?

**Comment by Javex** [comment]
Oh good question, I ran this on an Ubuntu that didn't have a recent enough tmux. It is possible to run `tmux show-options -g allow-passthrough` which will return "off" if disabled, "on" if enabled and return an error with exit code 1 if it doesn't exist (version too old). This would require invoking a subcommand though, is that something you want to do?

Alternatively, could we update the docs to say that it's necessary to allow this? There's also `set-clipboard` which must be "external" or "on", but not "off".

**Comment by theimpostor** [comment]
So both set-clipboard and allow-passthrough must be enabled? IMO it would
be better to run the commands and print an error message if conditions
aren't right, vs printing a bunch of escape chars to the terminal and
potentially messing up the terminal state.

**Comment by Javex** [comment]
I did a bit of testing and implemented a prototype that checks those options. During testing I realised that if the right options _aren't_ set and I print escape chars without accounting for tmux, it messed up the terminal state and I had to kill it. On the other hand, blindly printing the correct tmux escape sequence (with just the code in this PR) was accepted by tmux, but silently ignored. That is, the pane continues to work fine, but the clipboard isn't set.

So I think there's two options: Keep the PR as-is, which based on my particular version of tmux (3.4) worked out fine it seems. Or I push up my detection logic which can exit the program with an error code if any conditions aren't met. It's a fair bit of extra code though, as it's two options that need to be checked and their output needs to be parsed.

I don't mind which way, what would you prefer?

**Comment by theimpostor** [comment]
The PR as-is is definitely an improvement. Thanks!

**Pull request merged**
